const affirmations = [
  "Você consegue!",
  "Você vai descobrir",
  "Você é um biscoito inteligente! (inteligente tem boas ideias)",
  "Eu acredito em você!",
  "Sugar algo é o primeiro passo para ser bom em algo",
  "Lutar faz parte do aprendizado",
  "Tudo tem rachaduras - é assim que a luz entra",
  "Erros não o tornam menos capaz",
  "Somos todos obras em andamento",
  "Você é um humano capaz",
  "Você sabe mais do que pensa",
  "10x engenheiros são um mito",
  "Se tudo fosse fácil você estaria entediado",
  "Eu te admiro por aceitar isso",
  "Você é engenhoso e inteligente",
  "Você encontrará uma maneira",
  "Eu sei que você vai resolver isso",
  "Seu esforço significa que você está aprendendo",
  "Você está fazendo um ótimo trabalho",
  "Vai parecer mágico quando estiver funcionando",
  "Estou torcendo por você",
  "Sua mente está cheia de ideias brilhantes",
  "Você faz a diferença no mundo simplesmente existindo nele",
  "Você está aprendendo lições valiosas de si mesmo todos os dias",
  "Você é digno e merecedor de respeito",
  "Você sabe mais do que sabia ontem",
  "Você é uma inspiração",
  "Sua vida já é um milagre do acaso esperando por você para moldar seu destino",
  "Sua vida está prestes a ser incrível",
  "Nada é impossível. A própria palavra diz 'Eu sou possível!' (I'm-possible)",
  "O fracasso é apenas outra maneira de aprender a fazer algo certo",
  "Eu me dou permissão para fazer o que é certo para mim",
  "Você consegue",
  "Não é uma corrida, é uma maratona. Um passo de cada vez",
  "O sucesso é a realização progressiva de um objetivo digno",
  "Pessoas com objetivos são bem-sucedidas porque sabem para onde estão indo",
  "Tudo que você precisa é o plano, o roteiro e a coragem de seguir em frente ao seu destino",
  "O oposto de coragem em nossa sociedade não é covardia...",
  "Sempre que temos medo, é porque não sabemos o suficiente. Se entendêssemos o suficiente, nunca teríamos medo",
  "O passado não é igual ao futuro",
  "O caminho para o sucesso é tomar medidas massivas e determinadas",
  "É o que você pratica em particular que você será recompensado em público",
  "Pequeno progresso ainda é progresso",
  "Não se preocupe se você encontrar falhas em suas criações passadas, é porque você evoluiu",
  "Começar é o passo mais difícil - mas você pode fazê-lo",
  "Não se esqueça de aproveitar a viagem",
  "Não é um erro, é uma oportunidade de aprendizado",
];

module.exports = affirmations
